//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RPCRequest")]
  public partial class RPCRequest : global::ProtoBuf.IExtensible
  {
    public RPCRequest() {}
    
    private MSG _MsgID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private int _MsgIdentifier = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MsgIdentifier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MsgIdentifier
    {
      get { return _MsgIdentifier; }
      set { _MsgIdentifier = value; }
    }
    private byte[] _MsgData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"MsgData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] MsgData
    {
      get { return _MsgData; }
      set { _MsgData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RPCResponse")]
  public partial class RPCResponse : global::ProtoBuf.IExtensible
  {
    public RPCResponse() {}
    
    private MSG _MsgID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG MsgID
    {
      get { return _MsgID; }
      set { _MsgID = value; }
    }
    private int _MsgIdentifier = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MsgIdentifier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MsgIdentifier
    {
      get { return _MsgIdentifier; }
      set { _MsgIdentifier = value; }
    }
    private ErrorCode _ErrCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ErrCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ErrorCode ErrCode
    {
      get { return _ErrCode; }
      set { _ErrCode = value; }
    }
    private string _ErrMsg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ErrMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrMsg
    {
      get { return _ErrMsg; }
      set { _ErrMsg = value; }
    }
    private byte[] _MsgData = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MsgData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] MsgData
    {
      get { return _MsgData; }
      set { _MsgData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataInt")]
  public partial class DataInt : global::ProtoBuf.IExtensible
  {
    public DataInt() {}
    
    private int _Param;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Param
    {
      get { return _Param; }
      set { _Param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataLong")]
  public partial class DataLong : global::ProtoBuf.IExtensible
  {
    public DataLong() {}
    
    private long _Param;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Param
    {
      get { return _Param; }
      set { _Param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataString")]
  public partial class DataString : global::ProtoBuf.IExtensible
  {
    public DataString() {}
    
    private string _Param;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Param
    {
      get { return _Param; }
      set { _Param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"G2B_Connect")]
  public partial class G2B_Connect : global::ProtoBuf.IExtensible
  {
    public G2B_Connect() {}
    
    private string _Psw;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Psw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Psw
    {
      get { return _Psw; }
      set { _Psw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"B2G_Connect")]
  public partial class B2G_Connect : global::ProtoBuf.IExtensible
  {
    public B2G_Connect() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"G2B_ReqBattle")]
  public partial class G2B_ReqBattle : global::ProtoBuf.IExtensible
  {
    public G2B_ReqBattle() {}
    
    private long _UserID1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID1
    {
      get { return _UserID1; }
      set { _UserID1 = value; }
    }
    private int _UserLevel1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserLevel1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserLevel1
    {
      get { return _UserLevel1; }
      set { _UserLevel1 = value; }
    }
    private long _UserID2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UserID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID2
    {
      get { return _UserID2; }
      set { _UserID2 = value; }
    }
    private int _UserLevel2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserLevel2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserLevel2
    {
      get { return _UserLevel2; }
      set { _UserLevel2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"B2G_ReqBattle")]
  public partial class B2G_ReqBattle : global::ProtoBuf.IExtensible
  {
    public B2G_ReqBattle() {}
    
    private string _Token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private int _MapID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MapID
    {
      get { return _MapID; }
      set { _MapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"G2B_BattleReault")]
  public partial class G2B_BattleReault : global::ProtoBuf.IExtensible
  {
    public G2B_BattleReault() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_Login")]
  public partial class C2S_Login : global::ProtoBuf.IExtensible
  {
    public C2S_Login() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private string _Token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _ConfigID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ConfigID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ConfigID
    {
      get { return _ConfigID; }
      set { _ConfigID = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitInfo")]
  public partial class UnitInfo : global::ProtoBuf.IExtensible
  {
    public UnitInfo() {}
    
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _CardID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CardID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CardID
    {
      get { return _CardID; }
      set { _CardID = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
    private int _PosX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosX
    {
      get { return _PosX; }
      set { _PosX = value; }
    }
    private int _PosY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosY
    {
      get { return _PosY; }
      set { _PosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2C_StartBattle")]
  public partial class S2C_StartBattle : global::ProtoBuf.IExtensible
  {
    public S2C_StartBattle() {}
    
    private long _UserID1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID1
    {
      get { return _UserID1; }
      set { _UserID1 = value; }
    }
    private int _UserLevel1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserLevel1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserLevel1
    {
      get { return _UserLevel1; }
      set { _UserLevel1 = value; }
    }
    private long _UserID2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UserID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID2
    {
      get { return _UserID2; }
      set { _UserID2 = value; }
    }
    private int _UserLevel2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserLevel2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserLevel2
    {
      get { return _UserLevel2; }
      set { _UserLevel2 = value; }
    }
    private int _RandomSeed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"RandomSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RandomSeed
    {
      get { return _RandomSeed; }
      set { _RandomSeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_BattleResult")]
  public partial class C2S_BattleResult : global::ProtoBuf.IExtensible
  {
    public C2S_BattleResult() {}
    
    private int _WinnerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"WinnerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int WinnerID
    {
      get { return _WinnerID; }
      set { _WinnerID = value; }
    }
    private string _ReplayFile;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ReplayFile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ReplayFile
    {
      get { return _ReplayFile; }
      set { _ReplayFile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynTimestamp")]
  public partial class SynTimestamp : global::ProtoBuf.IExtensible
  {
    public SynTimestamp() {}
    
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _TurnIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TurnIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TurnIndex
    {
      get { return _TurnIndex; }
      set { _TurnIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynAction")]
  public partial class SynAction : global::ProtoBuf.IExtensible
  {
    public SynAction() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _TurnIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TurnIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TurnIndex
    {
      get { return _TurnIndex; }
      set { _TurnIndex = value; }
    }
    private BattleAction _Action;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BattleAction Action
    {
      get { return _Action; }
      set { _Action = value; }
    }
    private int _CardID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"CardID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CardID
    {
      get { return _CardID; }
      set { _CardID = value; }
    }
    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _PosX = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"PosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PosX
    {
      get { return _PosX; }
      set { _PosX = value; }
    }
    private int _PosY = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"PosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PosY
    {
      get { return _PosY; }
      set { _PosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynFull")]
  public partial class SynFull : global::ProtoBuf.IExtensible
  {
    public SynFull() {}
    
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private readonly global::System.Collections.Generic.List<UnitInfo> _Units = new global::System.Collections.Generic.List<UnitInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnitInfo> Units
    {
      get { return _Units; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynPos")]
  public partial class SynPos : global::ProtoBuf.IExtensible
  {
    public SynPos() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _PosX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosX
    {
      get { return _PosX; }
      set { _PosX = value; }
    }
    private int _PosY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosY
    {
      get { return _PosY; }
      set { _PosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynMoveTarget")]
  public partial class SynMoveTarget : global::ProtoBuf.IExtensible
  {
    public SynMoveTarget() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _PosX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosX
    {
      get { return _PosX; }
      set { _PosX = value; }
    }
    private int _PosY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PosY
    {
      get { return _PosY; }
      set { _PosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynAiTarget")]
  public partial class SynAiTarget : global::ProtoBuf.IExtensible
  {
    public SynAiTarget() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _TargetID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TargetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TargetID
    {
      get { return _TargetID; }
      set { _TargetID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynAttack")]
  public partial class SynAttack : global::ProtoBuf.IExtensible
  {
    public SynAttack() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _TargetID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TargetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TargetID
    {
      get { return _TargetID; }
      set { _TargetID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynSkill")]
  public partial class SynSkill : global::ProtoBuf.IExtensible
  {
    public SynSkill() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private int _TargetID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TargetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TargetID
    {
      get { return _TargetID; }
      set { _TargetID = value; }
    }
    private int _SkillID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynDead")]
  public partial class SynDead : global::ProtoBuf.IExtensible
  {
    public SynDead() {}
    
    private long _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Timestamp
    {
      get { return _Timestamp; }
      set { _Timestamp = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG")]
    public enum MSG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECT", Value=1)]
      CONNECT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_BATTLE", Value=2)]
      REQ_BATTLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_RESULT", Value=3)]
      BATTLE_RESULT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEART_BEAT", Value=1001)]
      HEART_BEAT = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GM_COMMAND", Value=1002)]
      GM_COMMAND = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=1003)]
      ERROR = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=1004)]
      LOGIN = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT", Value=1005)]
      LOGOUT = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_BATTLE", Value=2001)]
      START_BATTLE = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESUME_BATTLE", Value=2002)]
      RESUME_BATTLE = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISH_BATTLE", Value=2003)]
      FINISH_BATTLE = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_TIMESTAMP", Value=2004)]
      SYN_TIMESTAMP = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_ACTION", Value=2005)]
      SYN_ACTION = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_FULL", Value=2006)]
      SYN_FULL = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_POS", Value=3001)]
      SYN_POS = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_MOVE_TARGET", Value=3002)]
      SYN_MOVE_TARGET = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_AI_TARGET", Value=3003)]
      SYN_AI_TARGET = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_ATTACK", Value=3004)]
      SYN_ATTACK = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_SKILL", Value=3005)]
      SYN_SKILL = 3005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYN_DEAD", Value=3006)]
      SYN_DEAD = 3006
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACCOUNT_NOT_EXIST", Value=2)]
      ERR_ACCOUNT_NOT_EXIST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACCOUNT_ERR", Value=3)]
      ERR_ACCOUNT_ERR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PSW_ERR", Value=4)]
      ERR_PSW_ERR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACCOUNT_BAN", Value=5)]
      ERR_ACCOUNT_BAN = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_REGISTER_ACCOUNT_EXIST", Value=6)]
      ERR_REGISTER_ACCOUNT_EXIST = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ROLE_NAME_EXIST", Value=7)]
      ERR_ROLE_NAME_EXIST = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_REPEAT", Value=8)]
      ERR_LOGIN_REPEAT = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServerStatusType")]
    public enum ServerStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_NORMAL", Value=0)]
      SERVER_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_NEW", Value=1)]
      SERVER_NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_RECOMMENT", Value=2)]
      SERVER_RECOMMENT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_FULL", Value=3)]
      SERVER_FULL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_CLOSE", Value=4)]
      SERVER_CLOSE = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleAction")]
    public enum BattleAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELECT_CARD", Value=1)]
      SELECT_CARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUT_CARD", Value=2)]
      PUT_CARD = 2
    }
  
}