//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoCommon.proto
// Note: requires additional types generated from: ProtoBasis.proto
namespace comrt.comnet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMString")]
  public partial class PCMString : global::ProtoBuf.IExtensible
  {
    public PCMString() {}
    
    private string _arg = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMInt")]
  public partial class PCMInt : global::ProtoBuf.IExtensible
  {
    public PCMInt() {}
    
    private int _arg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMLong")]
  public partial class PCMLong : global::ProtoBuf.IExtensible
  {
    public PCMLong() {}
    
    private long _arg = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMInt2")]
  public partial class PCMInt2 : global::ProtoBuf.IExtensible
  {
    public PCMInt2() {}
    
    private int _arg = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private int _arg2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg2
    {
      get { return _arg2; }
      set { _arg2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMInt3")]
  public partial class PCMInt3 : global::ProtoBuf.IExtensible
  {
    public PCMInt3() {}
    
    private int _arg1 = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg1
    {
      get { return _arg1; }
      set { _arg1 = value; }
    }
    private int _arg2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg2
    {
      get { return _arg2; }
      set { _arg2 = value; }
    }
    private int _arg3 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"arg3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg3
    {
      get { return _arg3; }
      set { _arg3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMLongInt")]
  public partial class PCMLongInt : global::ProtoBuf.IExtensible
  {
    public PCMLongInt() {}
    
    private long _arg1 = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long arg1
    {
      get { return _arg1; }
      set { _arg1 = value; }
    }
    private int _arg2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arg2
    {
      get { return _arg2; }
      set { _arg2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCMLongRLong")]
  public partial class PCMLongRLong : global::ProtoBuf.IExtensible
  {
    public PCMLongRLong() {}
    
    private long _arg1 = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arg1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long arg1
    {
      get { return _arg1; }
      set { _arg1 = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _arg2 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> arg2
    {
      get { return _arg2; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCmLongList")]
  public partial class PCmLongList : global::ProtoBuf.IExtensible
  {
    public PCmLongList() {}
    
    private readonly global::System.Collections.Generic.List<long> _arg = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> arg
    {
      get { return _arg; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PComReq")]
  public partial class PComReq : global::ProtoBuf.IExtensible
  {
    public PComReq() {}
    
    private readonly global::System.Collections.Generic.List<long> _para1 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"para1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> para1
    {
      get { return _para1; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _para2 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"para2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> para2
    {
      get { return _para2; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _para3 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"para3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> para3
    {
      get { return _para3; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _para4 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"para4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> para4
    {
      get { return _para4; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}