//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBasis.proto
namespace comrt.comnet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonAnswer")]
  public partial class CommonAnswer : global::ProtoBuf.IExtensible
  {
    public CommonAnswer() {}
    
    private int _err_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"err_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int err_code
    {
      get { return _err_code; }
      set { _err_code = value; }
    }
    private string _errorMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorMsg
    {
      get { return _errorMsg; }
      set { _errorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eCommand")]
    public enum eCommand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOP", Value=0)]
      NOP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=1)]
      LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=2)]
      REGISTER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEARTBEAT", Value=3)]
      HEARTBEAT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN", Value=4)]
      JOIN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHECK_SESSION", Value=5)]
      CHECK_SESSION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_PLAYER_INFO", Value=6)]
      GET_PLAYER_INFO = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_NEW_ROLE", Value=7)]
      CREATE_NEW_ROLE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SERVER_LIST", Value=8)]
      LOGIN_SERVER_LIST = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_HERO", Value=9)]
      CREATE_HERO = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEARN_SKILL", Value=10)]
      LEARN_SKILL = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WHICH_GAME_SERVER", Value=11)]
      WHICH_GAME_SERVER = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_CONNECTION", Value=12)]
      EXIT_CONNECTION = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_SKILL", Value=13)]
      UPGRADE_SKILL = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIT_UP_EQUIP", Value=14)]
      FIT_UP_EQUIP = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRENTH_EQUIP", Value=15)]
      STRENTH_EQUIP = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_ADVANCE", Value=16)]
      HERO_ADVANCE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_UPGRADE_STAR", Value=17)]
      HERO_UPGRADE_STAR = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_SOME_HEROS_INFO", Value=18)]
      GET_SOME_HEROS_INFO = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROLE_INFO", Value=19)]
      GET_ROLE_INFO = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMODITY_LIST", Value=20)]
      COMMODITY_LIST = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_COMMODITY_GOODS", Value=21)]
      BUY_COMMODITY_GOODS = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_KNAPSACK_INFO", Value=22)]
      GET_KNAPSACK_INFO = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONE_KEY_FIT_UP_EQUIPS", Value=23)]
      ONE_KEY_FIT_UP_EQUIPS = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_HERO_LEVEL", Value=24)]
      UPDATE_HERO_LEVEL = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_SKILL_POINT", Value=25)]
      GET_SKILL_POINT = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_BUILD_INFO", Value=26)]
      GET_BUILD_INFO = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ASSERT_INFO", Value=27)]
      GET_ASSERT_INFO = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_BUILD_LEVEL", Value=28)]
      UPGRADE_BUILD_LEVEL = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONSTRUCT_BUILD", Value=29)]
      CONSTRUCT_BUILD = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLLECT_RESOURCE", Value=30)]
      COLLECT_RESOURCE = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCT_SOLIDERS", Value=40)]
      PRODUCT_SOLIDERS = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAIN_SOLIDERS", Value=41)]
      TRAIN_SOLIDERS = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_AND_PRODUCT_SOLIDERS", Value=42)]
      CHANGE_AND_PRODUCT_SOLIDERS = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_BUILD_RIGHT_NOW", Value=43)]
      UPGRADE_BUILD_RIGHT_NOW = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAIN_SOLIDER_RIGHT_NOW", Value=44)]
      TRAIN_SOLIDER_RIGHT_NOW = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCT_SOLIDER_RIGHT_NOW", Value=45)]
      PRODUCT_SOLIDER_RIGHT_NOW = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANCLE_UPGRADE_BUILD", Value=46)]
      CANCLE_UPGRADE_BUILD = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANCLE_TRAIN_SOLIDER", Value=47)]
      CANCLE_TRAIN_SOLIDER = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANCLE_PRODUCT_SOLIDER", Value=48)]
      CANCLE_PRODUCT_SOLIDER = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_PLYAYER_WORLD_MAP", Value=49)]
      GET_PLYAYER_WORLD_MAP = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REFRESH_CITY", Value=50)]
      REFRESH_CITY = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURVEY_CITY", Value=54)]
      SURVEY_CITY = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIT_DOWN_EQUIP", Value=51)]
      FIT_DOWN_EQUIP = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMBINE_EQUIP", Value=52)]
      COMBINE_EQUIP = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAPTER_PASS_LIST", Value=60)]
      CHAPTER_PASS_LIST = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_FUBEN_POS", Value=61)]
      GET_FUBEN_POS = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ENERGY", Value=62)]
      GET_ENERGY = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUYE_ENERGY", Value=63)]
      BUYE_ENERGY = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE_GOLD_LUCK_DRAW", Value=64)]
      FREE_GOLD_LUCK_DRAW = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIGLE_GOLD_LUCK_DRAW", Value=65)]
      SIGLE_GOLD_LUCK_DRAW = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEN_CONTINUE_GOLD_LUCK_DRAW", Value=66)]
      TEN_CONTINUE_GOLD_LUCK_DRAW = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE_DIAMOND_LUCK_DRAW", Value=67)]
      FREE_DIAMOND_LUCK_DRAW = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIGLE_DIAMOND_LUCK_DRAW", Value=68)]
      SIGLE_DIAMOND_LUCK_DRAW = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEN_CONTINUE_DIAMOND_LUCK_DRAW", Value=69)]
      TEN_CONTINUE_DIAMOND_LUCK_DRAW = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_LUCK_DRAW_INFO", Value=70)]
      GET_LUCK_DRAW_INFO = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_STAR_AWARD_LIST", Value=71)]
      GET_STAR_AWARD_LIST = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBTAIN_STAR_AWARD", Value=72)]
      OBTAIN_STAR_AWARD = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_PLAYER_SHOP_LIST", Value=73)]
      GET_PLAYER_SHOP_LIST = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_SHOP_GOOD", Value=74)]
      BUY_SHOP_GOOD = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MANAUL_REFRESH_SHOP", Value=75)]
      MANAUL_REFRESH_SHOP = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MAIL", Value=76)]
      SYS_MAIL = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_LIST", Value=77)]
      MAIL_LIST = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_MARK_READ", Value=78)]
      MAIL_MARK_READ = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_MAIL", Value=79)]
      SEND_MAIL = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBTAIN_MAIL_GOODS", Value=80)]
      OBTAIN_MAIL_GOODS = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONE_KEY_OBTAIN_MAIL_GOODS", Value=81)]
      ONE_KEY_OBTAIN_MAIL_GOODS = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_LIST", Value=82)]
      ATHTECLIC_LIST = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_RANK_LIST", Value=83)]
      ATHTECLIC_RANK_LIST = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_CHANCE", Value=84)]
      BUY_CHANCE = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_RANK_AWARD_INFO", Value=85)]
      ATHTECLIC_RANK_AWARD_INFO = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_RANK_AWARD_OBTAIN", Value=86)]
      ATHTECLIC_RANK_AWARD_OBTAIN = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_SCORE_AWARD_INFO", Value=87)]
      ATHTECLIC_SCORE_AWARD_INFO = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_SCORE_AWARD_OBTAIN", Value=88)]
      ATHTECLIC_SCORE_AWARD_OBTAIN = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHTECLIC_ENERY_LIST", Value=89)]
      ATHTECLIC_ENERY_LIST = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET_LINE_UP", Value=90)]
      SET_LINE_UP = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_PLAYER_INFO", Value=91)]
      OTHER_PLAYER_INFO = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_HERO_INF0", Value=92)]
      OTHER_HERO_INF0 = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USED_EXPBOOK", Value=93)]
      USED_EXPBOOK = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_LIST", Value=94)]
      GUILD_LIST = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPLY_JOIN_GUILD", Value=95)]
      APPLY_JOIN_GUILD = 95,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_MEMBER_LIST", Value=96)]
      GUILD_MEMBER_LIST = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEAL_WITH_JOIN_REQUEST", Value=97)]
      DEAL_WITH_JOIN_REQUEST = 97,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SLATE_FOR_VICE_CHAIRMAN", Value=98)]
      SLATE_FOR_VICE_CHAIRMAN = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KICKED_OUT_GUILD", Value=99)]
      KICKED_OUT_GUILD = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUIT_GUILD", Value=100)]
      QUIT_GUILD = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_GUILD", Value=101)]
      CREATE_GUILD = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_BUILD_LIST", Value=102)]
      GUILD_BUILD_LIST = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SALE_GOOD_TOSYS", Value=103)]
      SALE_GOOD_TOSYS = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_PROP_TO_GAINGOOD", Value=104)]
      USE_PROP_TO_GAINGOOD = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_LIST", Value=10000)]
      RANK_LIST = 10000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"READY_BT_FUBEN_NORMAL", Value=20010)]
      READY_BT_FUBEN_NORMAL = 20010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"READY_BT_FUBEN_ELITE", Value=20011)]
      READY_BT_FUBEN_ELITE = 20011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"READY_ATHTECLIC_CHALLENGE", Value=20016)]
      READY_ATHTECLIC_CHALLENGE = 20016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_BATTLE_RESULT", Value=20017)]
      GET_BATTLE_RESULT = 20017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"READY_BT_OCCUPY_CITY", Value=20018)]
      READY_BT_OCCUPY_CITY = 20018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOP_UP_FUBEN", Value=20012)]
      MOP_UP_FUBEN = 20012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOU_UP_FUBEN_INFO", Value=20013)]
      MOU_UP_FUBEN_INFO = 20013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUBEN_STAR_AWARD_INFO", Value=20014)]
      FUBEN_STAR_AWARD_INFO = 20014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBTAIN_FUBEN_STAR_AWARD", Value=20015)]
      OBTAIN_FUBEN_STAR_AWARD = 20015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_ELITE_COUNT", Value=20019)]
      BUY_ELITE_COUNT = 20019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT", Value=80001)]
      CHAT = 80001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADJUST_PLAYER_LEVEL", Value=900001)]
      ADJUST_PLAYER_LEVEL = 900001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_ADD_GOOD", Value=900002)]
      SYS_ADD_GOOD = 900002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_REDUCE_GOOD", Value=900003)]
      SYS_REDUCE_GOOD = 900003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPLY_MATCH_BATTLE", Value=10001)]
      APPLY_MATCH_BATTLE = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PUSH_SRVSTATUS", Value=50003)]
      SYS_PUSH_SRVSTATUS = 50003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_RELIEVE_GMWORLD", Value=50004)]
      SYS_RELIEVE_GMWORLD = 50004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_HEARTBEAT", Value=50005)]
      SYS_HEARTBEAT = 50005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MODIFY_USERPSW", Value=50006)]
      SYS_MODIFY_USERPSW = 50006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_CHANGE_SERVER_STATUS", Value=50007)]
      SYS_CHANGE_SERVER_STATUS = 50007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_SERVER_LIST", Value=50008)]
      SYS_SERVER_LIST = 50008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_ADD_USER_BLUELIGHT", Value=50009)]
      SYS_ADD_USER_BLUELIGHT = 50009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_CLEAR_USER_BLUELIGHT", Value=50010)]
      SYS_CLEAR_USER_BLUELIGHT = 50010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PROHIBIT_PARTNER_CHANNEL", Value=50012)]
      SYS_PROHIBIT_PARTNER_CHANNEL = 50012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PROHIBIT_PARTNER_CHANNEL_LIST", Value=50013)]
      SYS_PROHIBIT_PARTNER_CHANNEL_LIST = 50013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_CLEAR_PROHIBIT_PARTNER_CHANNEL", Value=50014)]
      SYS_CLEAR_PROHIBIT_PARTNER_CHANNEL = 50014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_REGISTER_USER_ACCOUNT", Value=50015)]
      SYS_REGISTER_USER_ACCOUNT = 50015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MINI_USER_ACCOUNT_LIST", Value=50016)]
      SYS_MINI_USER_ACCOUNT_LIST = 50016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_USER_ACCOUNT_LIST", Value=50017)]
      SYS_USER_ACCOUNT_LIST = 50017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_OPEN_QUEUE_UP", Value=50018)]
      SYS_OPEN_QUEUE_UP = 50018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_CLOSE_QUEUE_UP", Value=50019)]
      SYS_CLOSE_QUEUE_UP = 50019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_QUEUE_UP_STATUS", Value=50020)]
      SYS_QUEUE_UP_STATUS = 50020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_ACTIVATE_USER_ACCOUNT", Value=50021)]
      SYS_ACTIVATE_USER_ACCOUNT = 50021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_OPEN_USER_ACCOUNT_ACTIVATION", Value=50022)]
      SYS_OPEN_USER_ACCOUNT_ACTIVATION = 50022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_CLOSE_USER_ACCOUNT_ACTIVATION", Value=50023)]
      SYS_CLOSE_USER_ACCOUNT_ACTIVATION = 50023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_USER_ACCOUNT_ACTIVATION_STATUS", Value=50024)]
      SYS_USER_ACCOUNT_ACTIVATION_STATUS = 50024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MODIFY_MAINROLE_AUTHORITY", Value=50025)]
      SYS_MODIFY_MAINROLE_AUTHORITY = 50025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_SESSIONKEY", Value=50026)]
      SYS_SESSIONKEY = 50026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_EXIT_CONNECTION", Value=50027)]
      SYS_EXIT_CONNECTION = 50027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_RELOAD_RES", Value=50028)]
      SYS_RELOAD_RES = 50028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_SIMULATE_BATTLE", Value=50029)]
      SYS_SIMULATE_BATTLE = 50029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_BATTLE_RESULT", Value=50039)]
      SYS_BATTLE_RESULT = 50039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_NOTICE_BOARD", Value=90000)]
      SYS_NOTICE_BOARD = 90000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_SYSTEM_NOTICE", Value=90001)]
      SYS_SYSTEM_NOTICE = 90001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_RES_PATH_LIST", Value=5001029)]
      SYS_RES_PATH_LIST = 5001029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_ADDANDUPDATE_SERVERLIST", Value=60010)]
      SYS_ADDANDUPDATE_SERVERLIST = 60010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_EXIT", Value=60011)]
      SYS_EXIT = 60011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_USER_LOGIN", Value=60012)]
      SYS_USER_LOGIN = 60012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MEM_SNAPSHOT", Value=60013)]
      SYS_MEM_SNAPSHOT = 60013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_FORCED_TO_LOGOFF", Value=10010)]
      PUSH_FORCED_TO_LOGOFF = 10010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_BUILD_STATUS", Value=10011)]
      PUSH_BUILD_STATUS = 10011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_GET_BUILD", Value=10012)]
      PUSH_GET_BUILD = 10012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_GET_SOLIDER", Value=10013)]
      PUSH_GET_SOLIDER = 10013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_UNLOCK_SOLIDER", Value=10014)]
      PUSH_UNLOCK_SOLIDER = 10014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_TRAIN_SOLIDER_FINISH", Value=10015)]
      PUSH_TRAIN_SOLIDER_FINISH = 10015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_SHOP_REFRESH", Value=10016)]
      PUSH_SHOP_REFRESH = 10016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_COMMON_MAIL", Value=10017)]
      PUSH_COMMON_MAIL = 10017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_CHAT_CONTENT", Value=10018)]
      PUSH_CHAT_CONTENT = 10018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_NOTICE_BOARD", Value=10019)]
      PUSH_NOTICE_BOARD = 10019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_SYSTEM_NOTICE", Value=10020)]
      PUSH_SYSTEM_NOTICE = 10020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUSH_ROLELEVEL_UPGRADE", Value=10021)]
      PUSH_ROLELEVEL_UPGRADE = 10021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSPUSH_USER_ACCOUNT_ACTIVATION", Value=60001)]
      SYSPUSH_USER_ACCOUNT_ACTIVATION = 60001
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eErrorCode")]
    public enum eErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN", Value=1)]
      UNKNOWN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USERNAME_REPEAT", Value=3)]
      USERNAME_REPEAT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_USERNAME_ERROR", Value=4)]
      LOGIN_USERNAME_ERROR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_USERPASSWORD_ERROR", Value=5)]
      LOGIN_USERPASSWORD_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_PLAYER_ERROR", Value=6)]
      NO_PLAYER_ERROR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THE_USER_ACCOUNT_NOT_ACTIVATE", Value=7)]
      THE_USER_ACCOUNT_NOT_ACTIVATE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_NO_EXIST", Value=8)]
      ROLE_NO_EXIST = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE_PLAYER_EXIST_CACHE", Value=9)]
      OFFLINE_PLAYER_EXIST_CACHE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOAD_ONLINE_PLAYER_DOING", Value=10)]
      LOAD_ONLINE_PLAYER_DOING = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIST_THE_SAME_HERO", Value=11)]
      EXIST_THE_SAME_HERO = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIST_THE_SAME_SKILL", Value=12)]
      EXIST_THE_SAME_SKILL = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_REACH_CONITION_LEARN_SKILL", Value=13)]
      NOT_REACH_CONITION_LEARN_SKILL = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_HERO", Value=14)]
      NO_THIS_HERO = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_SKILL_POINT", Value=15)]
      NO_ENOUGH_SKILL_POINT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_LV_MAX_VALUE", Value=16)]
      SKILL_LV_MAX_VALUE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINJIE_REACH_MAX_LEVEL", Value=17)]
      PINJIE_REACH_MAX_LEVEL = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAR_REACH_MAX_LEVEL", Value=18)]
      STAR_REACH_MAX_LEVEL = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_SKILL", Value=19)]
      NO_THIS_SKILL = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KNASACK_IS_FULL", Value=20)]
      KNASACK_IS_FULL = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_SELL_OUT", Value=21)]
      GOOD_SELL_OUT = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_DIAMOND", Value=22)]
      NO_ENOUGH_DIAMOND = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_GOLD", Value=23)]
      NO_ENOUGH_GOLD = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_REACH_CONDITION_JINJIE", Value=24)]
      NOT_REACH_CONDITION_JINJIE = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_GOOD", Value=25)]
      NO_THIS_GOOD = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIST_THE_SAME_EQUIP", Value=26)]
      EXIST_THE_SAME_EQUIP = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_NOT_MATCH_HERO", Value=27)]
      EQUIP_NOT_MATCH_HERO = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_EQUIP_ALL_COMPETED", Value=28)]
      ALREADY_EQUIP_ALL_COMPETED = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THE_HOLE_NOT_MATCH_BUILD", Value=29)]
      THE_HOLE_NOT_MATCH_BUILD = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_REACH_MAX_LEVEL", Value=30)]
      BUILD_REACH_MAX_LEVEL = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_NUM_BEYOND_MAX", Value=31)]
      BUILD_NUM_BEYOND_MAX = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THE_HOLE_IS_USED", Value=32)]
      THE_HOLE_IS_USED = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILDING_NOW", Value=33)]
      BUILDING_NOW = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_UPGRADE_NOW", Value=34)]
      BUILD_UPGRADE_NOW = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_NOT_EXIST", Value=35)]
      BUILD_NOT_EXIST = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMITED_BY_PLAYER_LV", Value=36)]
      LEVEL_LIMITED_BY_PLAYER_LV = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_LIMITED_BY_MAIN_BUILD", Value=37)]
      LEVEL_LIMITED_BY_MAIN_BUILD = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_WOOD", Value=38)]
      NO_ENOUGH_WOOD = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_STONE", Value=39)]
      NO_ENOUGH_STONE = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_CAN_NOT_COLLECT", Value=40)]
      BUILD_CAN_NOT_COLLECT = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_BYOND_MAX_CAPACITY", Value=41)]
      RESOURCE_BYOND_MAX_CAPACITY = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_PRODUCTING_NOW", Value=42)]
      ALREADY_PRODUCTING_NOW = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCT_TYPE_NOT_MATCH", Value=43)]
      PRODUCT_TYPE_NOT_MATCH = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOME_SOLIDER_IS_UPGRADING", Value=44)]
      SOME_SOLIDER_IS_UPGRADING = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_LEVEL_REACH_MAX", Value=45)]
      SOLIDER_LEVEL_REACH_MAX = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_NOT_UNLOCK", Value=46)]
      SOLIDER_NOT_UNLOCK = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRILL_GROUND_UPGRADING", Value=47)]
      DRILL_GROUND_UPGRADING = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_TRAINING", Value=48)]
      SOLIDER_TRAINING = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INTERFACE_NO_OPEN", Value=49)]
      INTERFACE_NO_OPEN = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_INNER_PROBLEM", Value=50)]
      SERVER_INNER_PROBLEM = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ILLEGAL_STRING", Value=51)]
      ILLEGAL_STRING = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_NAME_NO_EXIST", Value=52)]
      USER_NAME_NO_EXIST = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SENSITIVE_CHARACTERS", Value=53)]
      SENSITIVE_CHARACTERS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEAT_ROLE_IDENTICAL_USER", Value=54)]
      REPEAT_ROLE_IDENTICAL_USER = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_LOAD_ERROR", Value=55)]
      RES_LOAD_ERROR = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_USER_CHANNEL", Value=56)]
      NO_THIS_USER_CHANNEL = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_NAME_REPEAT", Value=57)]
      ROLE_NAME_REPEAT = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_NAME_LENGTH_ILLEGA", Value=58)]
      ROLE_NAME_LENGTH_ILLEGA = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_IS_NOT_UPGRADING", Value=59)]
      BUILD_IS_NOT_UPGRADING = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_SERVER", Value=60)]
      NO_THIS_SERVER = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERVER_IS_MAINTAINING", Value=61)]
      ERVER_IS_MAINTAINING = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_IS_INVALID", Value=62)]
      SERVER_IS_INVALID = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EXIST_THE_SERVER", Value=63)]
      NO_EXIST_THE_SERVER = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_IS_MAINTAINING", Value=64)]
      SERVER_IS_MAINTAINING = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EXIST_SESSIONKEY", Value=65)]
      NO_EXIST_SESSIONKEY = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SESSIONKEY_EXPIRED", Value=66)]
      SESSIONKEY_EXPIRED = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_SOLIDER_IS_TRAINING", Value=67)]
      NO_SOLIDER_IS_TRAINING = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_SOLIDER_IS_PRODUCTING", Value=68)]
      NO_SOLIDER_IS_PRODUCTING = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EXIST_THE_PARTNER_CHANNEL", Value=71)]
      NO_EXIST_THE_PARTNER_CHANNEL = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THE_PARTNER_CHANNEL_PROHIBITED", Value=72)]
      THE_PARTNER_CHANNEL_PROHIBITED = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_SOCKET_CHANNEL", Value=73)]
      INVALID_SOCKET_CHANNEL = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MAX_CONNECT", Value=74)]
      SERVER_MAX_CONNECT = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_USER", Value=75)]
      INVALID_USER = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_CITY", Value=76)]
      NO_THIS_CITY = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIS_CITY_IN_PROTECTED", Value=77)]
      THIS_CITY_IN_PROTECTED = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVISIBLE_OF_THIS_CITY", Value=78)]
      INVISIBLE_OF_THIS_CITY = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OWER_OF_THIS_CITY", Value=79)]
      OWER_OF_THIS_CITY = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_REACH_REFRESH_TIME", Value=80)]
      NO_REACH_REFRESH_TIME = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CITY_INVALID_TIME", Value=201)]
      CITY_INVALID_TIME = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_SURVEY", Value=202)]
      ALREADY_SURVEY = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_THIS_FUBEN_POS", Value=81)]
      NO_THIS_FUBEN_POS = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_REACH_FUBEN_POS", Value=82)]
      NO_REACH_FUBEN_POS = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGY_ENERGY", Value=83)]
      NO_ENOUGY_ENERGY = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK_TIMES_BYOND_MAX", Value=84)]
      ATTACK_TIMES_BYOND_MAX = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_REACH_OBTAIN_CONDITION", Value=85)]
      NO_REACH_OBTAIN_CONDITION = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEATE_OBTAINED", Value=86)]
      REPEATE_OBTAINED = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_MOP_UP_TIMES", Value=87)]
      NO_MOP_UP_TIMES = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_REACH_3STARS", Value=88)]
      NO_REACH_3STARS = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_PASS_THIS_POS", Value=89)]
      NO_PASS_THIS_POS = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EXIST_ATTACKTARGET", Value=90)]
      NO_EXIST_ATTACKTARGET = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_FREE_TIMES", Value=91)]
      NO_ENOUGH_FREE_TIMES = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_IN_LUCKDRAW_TIME", Value=92)]
      NOT_IN_LUCKDRAW_TIME = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_NOT_INIT", Value=93)]
      SHOP_NOT_INIT = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_TOADDRESS_NO_EXIST", Value=94)]
      MAIL_TOADDRESS_NO_EXIST = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_MISMATCHING", Value=95)]
      MAIL_MISMATCHING = 95,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_EXPIRED", Value=96)]
      MAIL_EXPIRED = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_NOT_CONTAIN_EXTRAITEMS", Value=97)]
      MAIL_NOT_CONTAIN_EXTRAITEMS = 97,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THERE_HAS_FREE_TIMES", Value=98)]
      THERE_HAS_FREE_TIMES = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_CHALLENGE_AWARD_CALCULATING", Value=99)]
      ATHLETICS_CHALLENGE_AWARD_CALCULATING = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFENSER_PLAYER_MISMATCHING", Value=100)]
      DEFENSER_PLAYER_MISMATCHING = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_RANKING_CHECK_EXCEPTION", Value=101)]
      ATHLETICS_RANKING_CHECK_EXCEPTION = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_CHALLENGE_OUTOF_RANGE", Value=102)]
      ATHLETICS_CHALLENGE_OUTOF_RANGE = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_TIMES_USED_OUT", Value=103)]
      ATHLETICS_TIMES_USED_OUT = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_FIGHTING", Value=104)]
      ATHLETICS_FIGHTING = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATHLETICS_CHALLENGE_TARGET_RANKING_CHANGE", Value=105)]
      ATHLETICS_CHALLENGE_TARGET_RANKING_CHANGE = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_BATTLE", Value=106)]
      INVALID_BATTLE = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NUM_NOT_ENOUGH", Value=107)]
      ITEM_NUM_NOT_ENOUGH = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NOT_MATCH", Value=108)]
      ITEM_NOT_MATCH = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_MAIN_HERO", Value=109)]
      NO_MAIN_HERO = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_UNLOCK", Value=110)]
      SOLIDER_UNLOCK = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEATED_BATTLE_APPLY", Value=111)]
      REPEATED_BATTLE_APPLY = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODEL_TYPE_NOT_MATCHING", Value=112)]
      MODEL_TYPE_NOT_MATCHING = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODEL_LEVEL_NO_REACH_CONDITION", Value=113)]
      MODEL_LEVEL_NO_REACH_CONDITION = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODEL_NUM_NOT_ENOUGH", Value=114)]
      MODEL_NUM_NOT_ENOUGH = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_LUCK_STONE", Value=115)]
      NO_ENOUGH_LUCK_STONE = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORGE_BUILD_LEVEL_TOO_LOW", Value=116)]
      FORGE_BUILD_LEVEL_TOO_LOW = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_MATERIAL", Value=117)]
      NO_ENOUGH_MATERIAL = 117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ENOUGH_NUM", Value=118)]
      NO_ENOUGH_NUM = 118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONLINE_MAXCOUNT", Value=10000)]
      ONLINE_MAXCOUNT = 10000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSex")]
    public enum eSex
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN1", Value=0)]
      UNKNOWN1 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAN", Value=1)]
      MAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOMAN", Value=2)]
      WOMAN = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eServerType")]
    public enum eServerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN20", Value=0)]
      UNKNOWN20 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_COMMON", Value=1)]
      SERVER_COMMON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_RECOMMEND", Value=2)]
      SERVER_RECOMMEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_NEW", Value=3)]
      SERVER_NEW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_FIRESTORM", Value=4)]
      SERVER_FIRESTORM = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eServerStatus")]
    public enum eServerStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRVST_NONE", Value=0)]
      SRVST_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRVST_NORMAL", Value=1)]
      SRVST_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRVST_MAINTAINING", Value=2)]
      SRVST_MAINTAINING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRVST_INVALID", Value=3)]
      SRVST_INVALID = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSrvBusyDegree")]
    public enum eSrvBusyDegree
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN21", Value=0)]
      UNKNOWN21 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUN_WELL", Value=1)]
      RUN_WELL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULL", Value=2)]
      FULL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUSY", Value=3)]
      BUSY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALTED", Value=4)]
      HALTED = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eAccountActivation")]
    public enum eAccountActivation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AACT_NONE", Value=0)]
      AACT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AACT_NOT_ACTIVATED", Value=1)]
      AACT_NOT_ACTIVATED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AACT_BEINT_ACTIVATED", Value=2)]
      AACT_BEINT_ACTIVATED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eHpStatus")]
    public enum eHpStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN36", Value=0)]
      UNKNOWN36 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_ALIVE", Value=1)]
      HP_ALIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_GHOST", Value=2)]
      HP_GHOST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_HEAVEN_ROAD", Value=3)]
      HP_HEAVEN_ROAD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_DEAD", Value=4)]
      HP_DEAD = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eItem")]
    public enum eItem
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN6", Value=0)]
      UNKNOWN6 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWORD", Value=1)]
      SWORD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUN", Value=2)]
      GUN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOW", Value=3)]
      BOW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAN", Value=4)]
      FAN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOTH", Value=5)]
      CLOTH = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HARMOR", Value=6)]
      HARMOR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DECORATIONS", Value=7)]
      DECORATIONS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARBOOK", Value=8)]
      WARBOOK = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOULSTONE", Value=9)]
      SOULSTONE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY", Value=10)]
      CURRENCY = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_CARD", Value=11)]
      HERO_CARD = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=1000)]
      OTHER = 1000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSkillType")]
    public enum eSkillType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW46", Value=0)]
      UNKNOW46 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INITIATIVE", Value=1)]
      INITIATIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSIVITY", Value=2)]
      PASSIVITY = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ePriceType")]
    public enum ePriceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW12", Value=50)]
      UNKNOW12 = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIAMOND", Value=1)]
      DIAMOND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=2)]
      GOLD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD", Value=3)]
      WOOD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STONE", Value=4)]
      STONE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROPS", Value=5)]
      PROPS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENACURRENCY", Value=6)]
      ARENACURRENCY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPEDITION", Value=7)]
      EXPEDITION = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eGoodSortType")]
    public enum eGoodSortType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW14", Value=60)]
      UNKNOW14 = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_COMMON", Value=1)]
      GOOD_COMMON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_HOT", Value=2)]
      GOOD_HOT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_VIP", Value=3)]
      GOOD_VIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_NEW", Value=4)]
      GOOD_NEW = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_LIMIT_TIME", Value=5)]
      GOOD_LIMIT_TIME = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_LIMIT_NUM", Value=6)]
      GOOD_LIMIT_NUM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOOD_DISCOUNT", Value=7)]
      GOOD_DISCOUNT = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eUpgradeStatus")]
    public enum eUpgradeStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN13", Value=10)]
      UNKNOWN13 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_UPGRADE", Value=0)]
      NO_UPGRADE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRAD_DOING", Value=1)]
      UPGRAD_DOING = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDalayStatus")]
    public enum eDalayStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAS_INVALID", Value=0)]
      DAS_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAS_NORMAL", Value=1)]
      DAS_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAS_FINISHED", Value=2)]
      DAS_FINISHED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBuildType")]
    public enum eBuildType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN15", Value=70)]
      UNKNOWN15 = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MILITARY_CAMP", Value=1)]
      MILITARY_CAMP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RURAL_BUILD", Value=2)]
      RURAL_BUILD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUARRY_BUILD", Value=3)]
      QUARRY_BUILD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LUMBER_MILL", Value=4)]
      LUMBER_MILL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STONE_STORAGE", Value=5)]
      STONE_STORAGE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD_STORAGE", Value=6)]
      WOOD_STORAGE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TREASURY_BUILD", Value=7)]
      TREASURY_BUILD = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRILL_GROUND", Value=8)]
      DRILL_GROUND = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIN_CITY", Value=9)]
      MAIN_CITY = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORGE_BUILD", Value=10)]
      FORGE_BUILD = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACADEMY_BUILD", Value=11)]
      ACADEMY_BUILD = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eHoleSize")]
    public enum eHoleSize
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW16", Value=80)]
      UNKNOW16 = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMALL_SCALE", Value=1)]
      SMALL_SCALE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEDIUM_SCALE", Value=2)]
      MEDIUM_SCALE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LARGE_SCALE", Value=3)]
      LARGE_SCALE = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBuildStatus")]
    public enum eBuildStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW17", Value=81)]
      UNKNOW17 = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_STATUS", Value=1)]
      SOLIDER_STATUS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_STATUS", Value=2)]
      UPGRADE_STATUS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON_STATUS", Value=3)]
      COMMON_STATUS = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBuildAction")]
    public enum eBuildAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW18", Value=82)]
      UNKNOW18 = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILDING_FINISHED", Value=1)]
      BUILDING_FINISHED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_FINISHED", Value=2)]
      UPGRADE_FINISHED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSourceMapType")]
    public enum eSourceMapType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW20", Value=84)]
      UNKNOW20 = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLIDER_OUT", Value=1)]
      SOLIDER_OUT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STONE_OUT", Value=2)]
      STONE_OUT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD_OUT", Value=3)]
      WOOD_OUT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_OUT", Value=4)]
      GOLD_OUT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YUANBAO_OUT", Value=5)]
      YUANBAO_OUT = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eMapType")]
    public enum eMapType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW19", Value=83)]
      UNKNOW19 = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_CITY", Value=1)]
      PLAYER_CITY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOURCE_CITY", Value=3)]
      SOURCE_CITY = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eMissionType")]
    public enum eMissionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW21", Value=84)]
      UNKNOW21 = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISSION_NORMAL", Value=0)]
      MISSION_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISSION_LLELITE", Value=1)]
      MISSION_LLELITE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISSION_BOSS", Value=2)]
      MISSION_BOSS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISSION_BRANCH", Value=3)]
      MISSION_BRANCH = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eLLDegree")]
    public enum eLLDegree
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW22", Value=85)]
      UNKNOW22 = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LLD_NORMAL", Value=0)]
      LLD_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LLD_LLELITE", Value=1)]
      LLD_LLELITE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBattleSide")]
    public enum eBattleSide
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN23", Value=0)]
      UNKNOWN23 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIDE_ATTACKER", Value=1)]
      SIDE_ATTACKER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIDE_DEFENSER", Value=2)]
      SIDE_DEFENSER = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eLuckDraw")]
    public enum eLuckDraw
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOW24", Value=0)]
      UNKNOW24 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_LUCKDRAW", Value=1)]
      GOLD_LUCKDRAW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIAMOND_LUCKDRAW", Value=2)]
      DIAMOND_LUCKDRAW = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eShopType")]
    public enum eShopType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKONW25", Value=0)]
      UNKONW25 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_SUNDRY", Value=1)]
      GOLD_SUNDRY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DiAMOND_BLACK_MARKET", Value=2)]
      DiAMOND_BLACK_MARKET = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_ATHLECTICS", Value=3)]
      CURRENCY_ATHLECTICS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY_GUILD", Value=4)]
      CURRENCY_GUILD = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eChance")]
    public enum eChance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKONW26", Value=0)]
      UNKONW26 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAN_ATHLETICS", Value=1)]
      CHAN_ATHLETICS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAN_ENERGY", Value=2)]
      CHAN_ENERGY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAN_WOOD", Value=3)]
      CHAN_WOOD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAN_GOLD", Value=4)]
      CHAN_GOLD = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAN_STONE", Value=5)]
      CHAN_STONE = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eMailType")]
    public enum eMailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN27", Value=0)]
      UNKNOWN27 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_MS_SYS", Value=1)]
      MAIL_MS_SYS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_MS_PLAYER_INFO", Value=2)]
      MAIL_MS_PLAYER_INFO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_MS_CLIENT_FEEDBACK", Value=3)]
      MAIL_MS_CLIENT_FEEDBACK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_ATHLECTIC_AWARD", Value=4)]
      MAIL_ATHLECTIC_AWARD = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBattleResult")]
    public enum eBattleResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_NONE", Value=0)]
      BTR_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_WIN", Value=1)]
      BTR_WIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_FAIL", Value=2)]
      BTR_FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_PERFECT_VICTORY", Value=3)]
      BTR_PERFECT_VICTORY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_NARROW_VICTORY", Value=4)]
      BTR_NARROW_VICTORY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_LOSE_BY_A_NECK", Value=5)]
      BTR_LOSE_BY_A_NECK = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BTR_COMPLETE_DEFEAT", Value=6)]
      BTR_COMPLETE_DEFEAT = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRoleType")]
    public enum eRoleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_NONE", Value=0)]
      ROLE_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_LORD", Value=1)]
      ROLE_LORD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_HERO", Value=2)]
      ROLE_HERO = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eLineUpType")]
    public enum eLineUpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_NONE", Value=0)]
      BT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_PVP", Value=1)]
      BT_PVP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BT_PVE", Value=2)]
      BT_PVE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eGMemberOfficer")]
    public enum eGMemberOfficer
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_CHAIRMAN", Value=1)]
      GUILD_CHAIRMAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_VICE_CHAIRMAN", Value=2)]
      GUILD_VICE_CHAIRMAN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_COMMON_MEMBER", Value=3)]
      GUILD_COMMON_MEMBER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eWorldMapType")]
    public enum eWorldMapType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CITY_NONE", Value=0)]
      CITY_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_CITY_MAP", Value=1)]
      PLAYER_CITY_MAP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC_CITY_MAP", Value=2)]
      NPC_CITY_MAP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRank")]
    public enum eRank
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN28", Value=0)]
      UNKNOWN28 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAN_BATTLE_FEAT", Value=1)]
      RAN_BATTLE_FEAT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAN_FIGHTING", Value=2)]
      RAN_FIGHTING = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eChatObject")]
    public enum eChatObject
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN29", Value=0)]
      UNKNOWN29 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PLAYERTOPLAYER", Value=1)]
      CHAT_PLAYERTOPLAYER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PLAYERTOWORLD", Value=2)]
      CHAT_PLAYERTOWORLD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PLAYERTOGUILD", Value=3)]
      CHAT_PLAYERTOGUILD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_NOTICE_BOARD", Value=4)]
      CHAT_NOTICE_BOARD = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRoleAuthority")]
    public enum eRoleAuthority
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAUT_NONE", Value=0)]
      RAUT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAUT_COMMON", Value=1)]
      RAUT_COMMON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAUT_GAME_MASTER", Value=2)]
      RAUT_GAME_MASTER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAUT_HONORED_GUEST", Value=3)]
      RAUT_HONORED_GUEST = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRoleAttribute")]
    public enum eRoleAttribute
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_NONE", Value=0)]
      RATTR_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_WULI", Value=100)]
      RATTR_WULI = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_ZHILI", Value=101)]
      RATTR_ZHILI = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_TONGYU", Value=103)]
      RATTR_TONGYU = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_PHYS_ATK", Value=1)]
      RATTR_PHYS_ATK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_MAGIC_ATK", Value=2)]
      RATTR_MAGIC_ATK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_HP", Value=3)]
      RATTR_HP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_DAM_REDUCE", Value=4)]
      RATTR_DAM_REDUCE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_CRITIC_STRIKE", Value=5)]
      RATTR_CRITIC_STRIKE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_SUCK_BLOOD", Value=6)]
      RATTR_SUCK_BLOOD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_DAM_DEEPEN", Value=7)]
      RATTR_DAM_DEEPEN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_ATK_SPEED", Value=8)]
      RATTR_ATK_SPEED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RATTR_COOL_DOWN", Value=9)]
      RATTR_COOL_DOWN = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eCombineType")]
    public enum eCombineType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMBINE_NONE", Value=0)]
      COMBINE_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMBINE_GOLD", Value=1)]
      COMBINE_GOLD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMBINE_LUCK", Value=2)]
      COMBINE_LUCK = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFitUp")]
    public enum eFitUp
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIT_NONE", Value=0)]
      FIT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIT_DOWN", Value=1)]
      FIT_DOWN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIT_UP", Value=2)]
      FIT_UP = 2
    }
  
}