//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBattle.proto
// Note: requires additional types generated from: ProtoBasis.proto
// Note: requires additional types generated from: ProtoGmWorld.proto
namespace comrt.comnet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PAttack")]
  public partial class PAttack : global::ProtoBuf.IExtensible
  {
    public PAttack() {}
    
    private readonly global::System.Collections.Generic.List<long> _attackerId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attackerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> attackerId
    {
      get { return _attackerId; }
    }
  
    private comrt.comnet.PVector _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public comrt.comnet.PVector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private long _defenserId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"defenserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long defenserId
    {
      get { return _defenserId; }
      set { _defenserId = value; }
    }
    private long _attacker = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBattleReport")]
  public partial class PBattleReport : global::ProtoBuf.IExtensible
  {
    public PBattleReport() {}
    
    private long _attackerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attackerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long attackerId
    {
      get { return _attackerId; }
      set { _attackerId = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _attackHeroIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(15, Name=@"attackHeroIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> attackHeroIds
    {
      get { return _attackHeroIds; }
    }
  
    private long _defenserId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defenserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long defenserId
    {
      get { return _defenserId; }
      set { _defenserId = value; }
    }
    private comrt.comnet.PVector _pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public comrt.comnet.PVector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private comrt.comnet.eBattleSide _winner = comrt.comnet.eBattleSide.UNKNOWN23;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"winner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(comrt.comnet.eBattleSide.UNKNOWN23)]
    public comrt.comnet.eBattleSide winner
    {
      get { return _winner; }
      set { _winner = value; }
    }
    private int _awdExp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"awdExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdExp
    {
      get { return _awdExp; }
      set { _awdExp = value; }
    }
    private readonly global::System.Collections.Generic.List<comrt.comnet.PAwardPoint> _awardPoits = new global::System.Collections.Generic.List<comrt.comnet.PAwardPoint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"awardPoits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.PAwardPoint> awardPoits
    {
      get { return _awardPoits; }
    }
  
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private long _btTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"btTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long btTime
    {
      get { return _btTime; }
      set { _btTime = value; }
    }
    private int _awdGold = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"awdGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdGold
    {
      get { return _awdGold; }
      set { _awdGold = value; }
    }
    private int _awdStone = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"awdStone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdStone
    {
      get { return _awdStone; }
      set { _awdStone = value; }
    }
    private int _awdYuanbao = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"awdYuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdYuanbao
    {
      get { return _awdYuanbao; }
      set { _awdYuanbao = value; }
    }
    private int _awdWood = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"awdWood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdWood
    {
      get { return _awdWood; }
      set { _awdWood = value; }
    }
    private int _reserve1 = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"reserve1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reserve1
    {
      get { return _reserve1; }
      set { _reserve1 = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(100, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PMopUpFuben")]
  public partial class PMopUpFuben : global::ProtoBuf.IExtensible
  {
    public PMopUpFuben() {}
    
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private comrt.comnet.eLLDegree _llDegree = comrt.comnet.eLLDegree.UNKNOW22;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"llDegree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(comrt.comnet.eLLDegree.UNKNOW22)]
    public comrt.comnet.eLLDegree llDegree
    {
      get { return _llDegree; }
      set { _llDegree = value; }
    }
    private bool _force = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"force", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool force
    {
      get { return _force; }
      set { _force = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _attackerIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attackerIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> attackerIds
    {
      get { return _attackerIds; }
    }
  
    private int _mouUpTimes = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mouUpTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mouUpTimes
    {
      get { return _mouUpTimes; }
      set { _mouUpTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MouUpPerGain")]
  public partial class MouUpPerGain : global::ProtoBuf.IExtensible
  {
    public MouUpPerGain() {}
    
    private int _awdExp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"awdExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awdExp
    {
      get { return _awdExp; }
      set { _awdExp = value; }
    }
    private readonly global::System.Collections.Generic.List<comrt.comnet.PHeroAward> _heroAward = new global::System.Collections.Generic.List<comrt.comnet.PHeroAward>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heroAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.PHeroAward> heroAward
    {
      get { return _heroAward; }
    }
  
    private readonly global::System.Collections.Generic.List<comrt.comnet.PComItem> _awardItems = new global::System.Collections.Generic.List<comrt.comnet.PComItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"awardItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.PComItem> awardItems
    {
      get { return _awardItems; }
    }
  
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MopUpResult")]
  public partial class MopUpResult : global::ProtoBuf.IExtensible
  {
    public MopUpResult() {}
    
    private readonly global::System.Collections.Generic.List<comrt.comnet.MouUpPerGain> _awardCollections = new global::System.Collections.Generic.List<comrt.comnet.MouUpPerGain>();
    [global::ProtoBuf.ProtoMember(1, Name=@"awardCollections", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.MouUpPerGain> awardCollections
    {
      get { return _awardCollections; }
    }
  
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PMopUpInfo")]
  public partial class PMopUpInfo : global::ProtoBuf.IExtensible
  {
    public PMopUpInfo() {}
    
    private int _usedTimes = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"usedTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int usedTimes
    {
      get { return _usedTimes; }
      set { _usedTimes = value; }
    }
    private int _remainTimes = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"remainTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainTimes
    {
      get { return _remainTimes; }
      set { _remainTimes = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PUnitObtain")]
  public partial class PUnitObtain : global::ProtoBuf.IExtensible
  {
    public PUnitObtain() {}
    
    private readonly global::System.Collections.Generic.List<int> _obtainIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"obtainIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> obtainIds
    {
      get { return _obtainIds; }
    }
  
    private comrt.comnet.eLLDegree _llDegree = comrt.comnet.eLLDegree.UNKNOW22;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"llDegree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(comrt.comnet.eLLDegree.UNKNOW22)]
    public comrt.comnet.eLLDegree llDegree
    {
      get { return _llDegree; }
      set { _llDegree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PFubenGift")]
  public partial class PFubenGift : global::ProtoBuf.IExtensible
  {
    public PFubenGift() {}
    
    private int _chapterId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private readonly global::System.Collections.Generic.List<comrt.comnet.PUnitObtain> _starAwards = new global::System.Collections.Generic.List<comrt.comnet.PUnitObtain>();
    [global::ProtoBuf.ProtoMember(2, Name=@"starAwards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.PUnitObtain> starAwards
    {
      get { return _starAwards; }
    }
  
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PFubenStarAwardInfo")]
  public partial class PFubenStarAwardInfo : global::ProtoBuf.IExtensible
  {
    public PFubenStarAwardInfo() {}
    
    private readonly global::System.Collections.Generic.List<comrt.comnet.PFubenGift> _fubenGiftList = new global::System.Collections.Generic.List<comrt.comnet.PFubenGift>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fubenGiftList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<comrt.comnet.PFubenGift> fubenGiftList
    {
      get { return _fubenGiftList; }
    }
  
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PGetBattleResult")]
  public partial class PGetBattleResult : global::ProtoBuf.IExtensible
  {
    public PGetBattleResult() {}
    
    private long _battleId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long battleId
    {
      get { return _battleId; }
      set { _battleId = value; }
    }
    private comrt.comnet.eBattleResult _btResult = comrt.comnet.eBattleResult.BTR_NONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"btResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(comrt.comnet.eBattleResult.BTR_NONE)]
    public comrt.comnet.eBattleResult btResult
    {
      get { return _btResult; }
      set { _btResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBattlVerify")]
  public partial class PBattlVerify : global::ProtoBuf.IExtensible
  {
    public PBattlVerify() {}
    
    private long _battleId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long battleId
    {
      get { return _battleId; }
      set { _battleId = value; }
    }
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}