//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AttachTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(AttachType));
		L.RegVar("ABSORIGIN", get_ABSORIGIN, null);
		L.RegVar("ABSORIGIN_FOLLOW", get_ABSORIGIN_FOLLOW, null);
		L.RegVar("WORLDORIGIN", get_WORLDORIGIN, null);
		L.RegVar("CUSTOMORIGIN", get_CUSTOMORIGIN, null);
		L.RegVar("CUSTOMORIGIN_FOLLOW", get_CUSTOMORIGIN_FOLLOW, null);
		L.RegVar("POINT", get_POINT, null);
		L.RegVar("POINT_FOLLOW", get_POINT_FOLLOW, null);
		L.RegVar("ROOTBONE_FOLLOW", get_ROOTBONE_FOLLOW, null);
		L.RegVar("EYES_FOLLOW", get_EYES_FOLLOW, null);
		L.RegVar("WORLDPOINT", get_WORLDPOINT, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ABSORIGIN(IntPtr L)
	{
		ToLua.Push(L, AttachType.ABSORIGIN);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ABSORIGIN_FOLLOW(IntPtr L)
	{
		ToLua.Push(L, AttachType.ABSORIGIN_FOLLOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WORLDORIGIN(IntPtr L)
	{
		ToLua.Push(L, AttachType.WORLDORIGIN);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CUSTOMORIGIN(IntPtr L)
	{
		ToLua.Push(L, AttachType.CUSTOMORIGIN);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CUSTOMORIGIN_FOLLOW(IntPtr L)
	{
		ToLua.Push(L, AttachType.CUSTOMORIGIN_FOLLOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_POINT(IntPtr L)
	{
		ToLua.Push(L, AttachType.POINT);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_POINT_FOLLOW(IntPtr L)
	{
		ToLua.Push(L, AttachType.POINT_FOLLOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ROOTBONE_FOLLOW(IntPtr L)
	{
		ToLua.Push(L, AttachType.ROOTBONE_FOLLOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EYES_FOLLOW(IntPtr L)
	{
		ToLua.Push(L, AttachType.EYES_FOLLOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WORLDPOINT(IntPtr L)
	{
		ToLua.Push(L, AttachType.WORLDPOINT);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		AttachType o = (AttachType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

