//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TeamFlagWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(TeamFlag));
		L.RegVar("BOTH", get_BOTH, null);
		L.RegVar("ENEMY", get_ENEMY, null);
		L.RegVar("FRIENDLY", get_FRIENDLY, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BOTH(IntPtr L)
	{
		ToLua.Push(L, TeamFlag.BOTH);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ENEMY(IntPtr L)
	{
		ToLua.Push(L, TeamFlag.ENEMY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FRIENDLY(IntPtr L)
	{
		ToLua.Push(L, TeamFlag.FRIENDLY);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		TeamFlag o = (TeamFlag)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

